name: Deploy Solo Noticias (QA)

on:
  push:
    branches:
      - main
    paths:  # <--- AQUÍ ESTÁ EL FILTRO
      - 'src/posts/**'        # Cualquier cambio en tus .md
      - 'src/assets/img/**'   # Cualquier imagen nueva

permissions:
  contents: write
  pages: write
  id-token: write

jobs:
  test-and-deploy: # Le cambiamos el nombre para diferenciar
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      # Podrías agregar pasos extra aquí, como pruebas de código (Linter)
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Build Eleventy (Core Update)
        run: npx @11ty/eleventy --output _site

      - name: Deploy a QA (Noticias)
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: qa
          publish_dir: ./_site
          commit_message: "Auto-deploy: Actualización de noticias" # <--- Personalizado